### PR TITLE
feat: add config option "telescope.reset_prompt_after_deletion"

### PR DESCRIPTION
**Pull request by adoyle-h**
User can decide whether reset prompt or not.

### CODE REVIEW

**Comment by olimorris** [comment]
What's the problem statement here? I'm loathed to add any more config options unless truly neccessary

**Comment by adoyle-h** [comment]
@olimorris When delete lots of sessions in telescope, it always reset prompt. So that I need to type the long file path again.

I use `require('telescope').extensions.persisted.persisted { default_text = vim.fn.getcwd():sub(#os.getenv('HOME') + 2) }` to open telescope window with default prompt.

**Comment by olimorris** [comment]
Ah okay. Should we keep this to true by default? Feels like a logical inclusion.

**Comment by adoyle-h** [comment]
Yes. It's still `true` for avoiding breaking change.

**Comment by olimorris** [comment]
Can you remove this from the `config.lua` file and I'll then merge

**Comment by adoyle-h** [comment]
Why remove the default config? `config.refresh_reset_prompt` will be `nil`.

**Comment by adoyle-h** [comment]
What? This PR adds an option. If remove it, merging the PR is meaningless. My purpose is "User can decide whether reset prompt or not."

**Comment by adoyle-h** [comment]
> @olimorris When delete lots of sessions in telescope, it always reset prompt. So that I need to type the long file path again.
> 
> I use `require('telescope').extensions.persisted.persisted { default_text = vim.fn.getcwd():sub(#os.getenv('HOME') + 2) }` to open telescope window with default prompt.

@olimorris How to implement this logic without adding the config option? Is there any workaround?

**Comment by adoyle-h** [comment]
@olimorris Done.

**Pull request merged**
