### PR TITLE
feat: add icons and colors to telescope picker

### PR DESCRIPTION
**Pull request by calops**
Prettier rendering in the telescope picker.

Note: This uses nerd-font icons right know, and yeah, it's probably not ideal as the only option. Maybe we can make this configurable?

Screenshot 2024-04-20 at 21 07 49

### CODE REVIEW

**Comment by olimorris** [comment]
Love this!! Great suggestion and PR!

I share your thought too regarding icons...could we make it configurable and also the option to turn them off? I'd like it on by default but in case someone doesn't have a patched font installed, they can easily turn it off

**Comment by calops** [comment]
There you go, I added config options.

**Comment by olimorris** [comment]
It's looking great...except if you have the cursorline on (`vim.wo.cursorline = true`) then the background of the text doesn't change:

2024-04-21 19_09_50 - WezTerm@2x

You can see on the `neotest-rspec` line, the icon's bg color changes but the text doesn't.

This was'nt the case before the PR unfortunately:

2024-04-21 19_15_00 - WezTerm@2x

**Comment by calops** [comment]
Indeed, should be fixed now.

**Comment by olimorris** [comment]
Now we're cooking! Thanks again.

**Pull request merged**
