### PR TITLE
wip: lazy integration

### PR DESCRIPTION
**Pull request by olimorris**

### CODE REVIEW

**Comment by olimorris** [comment]
@Saafo, try this and let me know if it works

**Comment by Saafo** [comment]
@olimorris Thanks for the integration! But maybe there's still some issue to be fix:

To reproduce, you can clean another plugin or add a new plugin, and restart nvim, after lazy automatically installed the missing plugin, the editor still opened in the small window 🤔

image

And about the minimal config: I didn't have a minimal config when I opened the issue #78 , but now I found one here: https://github.com/ayamir/nvimdots/issues/790#issuecomment-1587227939, maybe you can use it to help to reproduce! 🙏

**Comment by olimorris** [comment]
There's a minimal config when you open a new bug report. It creates everything for you.

Okay, wonder if there's something I can do to close that float window...

**Comment by olimorris** [comment]
@Saafo - Worth checking out this [post](https://github.com/rmagatti/auto-session/issues/223#issuecomment-1666658887)

**Comment by Saafo** [comment]
> @Saafo - Worth checking out this [post](https://github.com/rmagatti/auto-session/issues/223#issuecomment-1666658887)

@olimorris Thanks! I'm also subscribing to that post. I think it can works, but I'm planning to wait for a more robust and elegant way to achieve it. (Maybe it depends on lazy's API for its window closing event or something like that)

**Comment by Saafo** [comment]
Hi @olimorris this issue is fixed by https://github.com/rmagatti/auto-session/pull/305 in auto-session, maybe we can fix it in the same way?

**Pull request closed without merging**
